# Generated by Django 4.0.3 on 2022-04-19 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_about_contact_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='organization',
            new_name='Organization',
        ),
    ]
