# Generated by Django 4.0.3 on 2022-04-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_organization_feedback_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Organization',
            new_name='organization',
        ),
    ]
